CREATE TABLE financial_records (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMBER(19, 2) NOT NULL,
    type VARCHAR2(20 CHAR) NOT NULL,
    category VARCHAR2(50 CHAR) NOT NULL,
    description VARCHAR2(500 CHAR),
    transaction_date DATE NOT NULL,
    deleted NUMBER(1) DEFAULT 0 NOT NULL,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_financial_records_type CHECK (type IN ('INCOME', 'EXPENSE')),
    CONSTRAINT chk_financial_records_deleted CHECK (deleted IN (0, 1)),
    CONSTRAINT chk_financial_records_amount CHECK (amount > 0)
);

CREATE INDEX idx_financial_type_date_deleted ON financial_records (type, transaction_date, deleted);
CREATE INDEX idx_financial_category_date_deleted ON financial_records (category, transaction_date, deleted);
CREATE INDEX idx_financial_created_at ON financial_records (created_at);
