CREATE TABLE users (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50 CHAR) NOT NULL,
    email VARCHAR2(120 CHAR) NOT NULL,
    password_hash VARCHAR2(255 CHAR) NOT NULL,
    role VARCHAR2(20 CHAR) NOT NULL,
    status VARCHAR2(20 CHAR) NOT NULL,
    deleted NUMBER(1) DEFAULT 0 NOT NULL,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT chk_users_role CHECK (role IN ('VIEWER', 'ANALYST', 'ADMIN')),
    CONSTRAINT chk_users_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT chk_users_deleted CHECK (deleted IN (0, 1))
);

CREATE INDEX idx_users_role_status_deleted ON users (role, status, deleted);
CREATE INDEX idx_users_email_deleted ON users (email, deleted);
CREATE INDEX idx_users_username_deleted ON users (username, deleted);
